config/routes.rb
Rails.application.routes.draw do
  get 'pages/one'
  get 'pages/two'
  get 'pages/three'

  root 'pages#one'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def one
  end

  def two
  end

  def three
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

  </head>

  <body class="container">
 
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
     
      <div class="container-fluid">
 
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
 
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <%= link_to 'one', pages_one_path, class:"nav-link"%>
            </li>
            <li class="nav-item">
              <%= link_to 'two', pages_two_path, class:"nav-link"%>
            </li>
            <li class="nav-item">
              <%= link_to 'three', pages_three_path, class:"nav-link"%>
            </li>
          </ul>
        </div>
 
        </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/pages/one.html.erb
<h1> Ana Teresa Doña </h1>
<p>Find me in app/views/pages/one.html.erb</p>

app/views/pages/three.html.erb
<h2> Título en h2 para página three </h2>
<p>Laborum sunt velit magna ex et ex dolor deserunt consectetur eu eu ex mollit. Eu anim labore voluptate incididunt commodo quis quis aliqua. Ut eu culpa incididunt anim laborum dolor qui. Dolor aliquip officia eiusmod anim ex minim nostrud sit quis ullamco aliqua ut sit proident. Pariatur labore fugiat non aute veniam ex sunt reprehenderit pariatur proident.</p>

app/views/pages/two.html.erb
<h1>Pages#two</h1>
<p>Find me in app/views/pages/two.html.erb</p>

<%= image_tag 'rake_routes.jpg' %>